export const actionTypes = {
    // Action Types List
    LIST_BANNER: "LIST_BANNER",
    LIST_CITY: "LIST_CITY",
    LIST_TRANSACTION: "LIST_TRANSACTION",
    TOTAL_TRANSACTION: "TOTAL_TRANSACTION",
    LINE_CHART: "LINE_CHART",
    GLOBAL_CHART: "GLOBAL_CHART",
    PIE_DOUBLE_CHART: "PIE_DOUBLE_CHART",
    TOTAL_SALES_TODAY: "TOTAL_SALES_TODAY",
    POINTS_COLLECTED_TODAY: "POINTS_COLLECTED_TODAY",
    ITEMS_SOLD_TODAY: "ITEMS_SOLD_TODAY",
    BRUSH_BAR_CHART: "BRUSH_BAR_CHART",
    LIST_BANK_QUESTION: "LIST_BANK_QUESTION",
    TOTAL_BANK_QUESTION: "TOTAL_BANK_QUESTION"

}